# encoding: utf-8

require 'closure-compiler'
require 'coffeelint'
require 'coffee-script'

require 'date'
require 'pathname'

require 'wiselinks/version'

module Wiselinks
  class Builder
    include Rake::DSL if defined? Rake::DSL

    class << self
      attr_accessor :instance

      def install
        self.new.install
      end
    end


    def install
      # desc "Build #{self.name}-#{self.version} CoffeeScript sources."
      # task 'build' do
      #   Rake::Task["coffee:lint"].invoke
      #   Rake::Task["coffee:build"].invoke
      # end

      namespace :coffee do
        desc "Run CoffeeLint over #{self.name}-#{self.version} sources."
        task 'lint' do
          Coffeelint.lint_dir(self.sources) do |filename, lint_report|
            Coffeelint.display_test_results(filename, lint_report)
          end
        end

        desc "Build #{self.name}-#{self.version} CoffeeScript sources."
        task 'build' do
          sh("rm ./build/*")

          # Compile
          #
          File.open("./build/#{self.name_with_version}.js", "w") do |js|
            js << "#{self.declaration}\n"
            coffee = self.coffee_sources.map(&:read).join("\n")
            js << "// Generated by CoffeeScript #{CoffeeScript.version}\n"
            js << CoffeeScript.compile(coffee)
            js << self.js_sources.map(&:read).join("\n")
          end

          # Minimize
          #
          sh("java -jar ./compiler.jar --charset UTF-8 --js ./build/#{self.name_with_version}.js --js_output_file=./build/#{self.name_with_version}.min.js")

          # Gzip
          #
          sh("gzip -9 -c ./build/#{self.name_with_version}.min.js > ./build/#{self.name_with_version}.min.js.gz")
        end
      end

    end

  protected

    def sources
      File.expand_path('../../assets/javascripts', __FILE__)
    end

    def js_sources
      Pathname.glob(File.join(self.sources, "**/*.js")).sort
    end

    def coffee_sources
      Pathname.glob(File.join(self.sources, "**/*.js.coffee")).sort
    end

    def version
      self.specification.version
    end

    def declaration
<<-EOS
/**
 * #{self.name.capitalize}-#{self.version}
 * @copyright 2012-#{Date.today.year} #{self.specification.authors.join(', ')}
 * @preserve https://github.com/igor-alexandrov/wiselinks
 */
EOS
    end

    def name
      self.specification.name
    end

    def name_with_version
      [self.name, self.version].join('-')
    end

    def specification
      @specification ||= Gem.loaded_specs['wiselinks']
    end
  end
end

Wiselinks::Builder.install
